### ISSUE TITLE
Add to RSD

### ISSUE THREAD

**Issue by fdiblen** [ci-for-science/self-hosted-runners#3]
Do what the title says :stuck_out_tongue:

**Comment by jspaaks** [comment]
https://www.research-software.nl/admin/software/090bb77c-8808-4957-b573-2d1567e8563a
for the moment set to ``unpublished`` until we have a release and update the FIXMEs in the features description

**Comment by fdiblen** [comment]
Probably we should do that now.

**Comment by jspaaks** [comment]
https://research-software.nl/software/self-hosted-runners
