### ISSUE TITLE
Improve the playbook

### ISSUE THREAD

**Issue by fdiblen** [ci-for-science/self-hosted-runners#31]
- [x] user input for the repo. Currently it is hardcoded and uses SCM-NV/qmflows-namd
- [x] more descriptive task names 
- [ ] add tags for the tasks
- [ ] add new stop runner task

**Comment by sverhoeven** [comment]
Instead of writing our own installer tasks in a playbook we could also use an existing role like https://galaxy.ansible.com/monolithprojects/github_actions_runner

That role needs root to install stuff so it can not be used on a cartesius #17

**Comment by jspaaks** [comment]
I marked the first task as done 
https://github.com/NLESC-JCER/linux_actions_runner/blob/01d11210450283a9d5d78545e01bfd31106843a1/ubuntu-virtualbox/playbook-set-up-runner.yml#L6-L14

Also second task done

**Comment by jspaaks** [comment]
Can we make this issue title more specific?
