### ISSUE TITLE
instructions to create a vm on hpc cloud

### ISSUE THREAD

**Issue by fdiblen** [ci-for-science/self-hosted-runners#34]

**Comment by sverhoeven** [comment]
Make sure to explain that the hostname of the VM in `ubuntu-surf-hpc-cloud/simple/hosts` and `ubuntu-surf-hpc-cloud/gpu-houston/hosts` should be updated when someone creates there own VM in the HPC cloud.

**Comment by fdiblen** [comment]
@sverhoeven maybe we should have hosts.example file for each guide but not hosts file. This will solve the problem.

I also added a link in ubuntu-surf-hpc-cloud to point to HPC Cloud documentation. Users can read it to create a VM.

**Comment by sverhoeven** [comment]
We should only commit a files that don't have to be changed by a potential user. Using *.example for files that the user should copy is my preferred way.

**Comment by fdiblen** [comment]
We did point to SURF HPC Cloud docs. 
https://doc.hpccloud.surfsara.nl/
See
https://github.com/ci-for-science/self-hosted-runners/blame/96ad114d1aa38861749f634dcdaa9ece59709b3a/ubuntu-surf-hpc-cloud/README.md
