### ISSUE TITLE
prompt for repository in playbook

### ISSUE THREAD

**Issue by fdiblen** [ci-for-science/self-hosted-runners#42]
Ansible playbook should ask for user input to set "repo" variable.

**Comment by jspaaks** [comment]
https://github.com/NLESC-JCER/linux_actions_runner/blob/01d11210450283a9d5d78545e01bfd31106843a1/ubuntu-virtualbox/playbook-set-up-runner.yml#L6-L14

**Comment by sverhoeven** [comment]
Also on windows / hpc guide see https://github.com/ci-for-science/self-hosted-runners/blob/master/windows-surf-hpc-cloud/ci-hpc-prompt.png
