### ISSUE TITLE
naming inventory files

### ISSUE THREAD

**Issue by fdiblen** [ci-for-science/self-hosted-runners#51]
Decide how we want to name ansible inventory files.
Options:
- inventory
- inventory.y(a)ml
- hosts
- hosts.y(a)ml

**Comment by jspaaks** [comment]
The docs say the default invenotry file should be called ``hosts``, but it is located in ``/etc/ansible``. It seems that a ``./etc/ansible/hosts`` is not being picked up.

https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
