### ISSUE TITLE
redistribution of content 

### ISSUE THREAD

**Issue by jspaaks** [ci-for-science/self-hosted-runners#53]
We currently have content in a couple of places, e.g.:

- [x] https://github.com/NLESC-JCER/linux_actions_runner
- [x] https://github.com/NLESC-JCER/ci_for_science
- [ ] https://github.com/NLESC-JCER/EigenCuda
- [x] https://github.com/NLESC-JCER/gitlab_runner ?
- [x] https://github.com/sverhoeven/justatest (private) ?
- [ ] etc

I propose to consolidate these into their own github organization, e.g. https://github.com/ci-for-science

**Comment by sverhoeven** [comment]
https://github.com/sverhoeven/justatest has been copied to https://github.com/ci-for-science/python-example1

**Comment by jspaaks** [comment]
Enough done
