### ISSUE TITLE
Remove self_hosted_ci.yml

### ISSUE THREAD

**Issue by sverhoeven** [ci-for-science/self-hosted-runners#69]
The `.github/workflows/self_hosted_ci.yml` can be removed as the example repos have those workflows. 

Also it makes Pull Requests fail due to offline runner.

**Comment by jspaaks** [comment]
I'd suggest also removing ``github_hosted_ci.yml``, neither workflow is doing anything useful, and they need to be in other repos anyway.

**Comment by jspaaks** [comment]
PR https://github.com/ci-for-science/self-hosted-runners/pull/73

**Comment by jspaaks** [comment]
done
